version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules # Tạo volume riêng cho node_modules
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - .:/var/www/html  # Mount mã nguồn Laravel vào container
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1
      MYSQL_DATABASE: laravel
      MYSQL_USER: root12
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql 
    ports:
      - "3308:3306"
    networks:
      - laravel
  
  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"  # Mở cổng  
    volumes:
    - redis_data:/data
    networks:
      - laravel

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis  # Đảm bảo RedisInsight biết Redis container nào để kết nối
    depends_on:
      - redis  # RedisInsight sẽ khởi động sau Redis
    networks:
      - laravel

  mongodb:
    image: mongo:latest
    container_name: laravel_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
  mongodb_data:
  redis_data:
