# version: '3.8'

# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: php-app
#     container_name: Dashboard
#     ports:
#       - "8000:80" 
#     volumes:
#       - .:/var/www/html
#     depends_on:
#       - mysql
#       - redis
#       # - mongodb

#   mysql:
#     image: mysql:latest
#     container_name: mysql_db
#     environment:
#       MYSQL_RANDOM_ROOT_PASSWORD: "yes"
#       MYSQL_DATABASE: laravel
#     ports:
#       - "3307:3306"

#   redis:
#     image: redis:latest
#     container_name: redis_db
#     ports:
#       - "6379:6379"

  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb_db
  #   ports:
  #     - "27017:27017"
version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - .:/var/www/html  # Mount mã nguồn Laravel vào container
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1
      MYSQL_DATABASE: laravel
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - laravel
  
  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"  # Mở cổng Redis
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
